# Generated by Django 3.0.8 on 2020-10-12 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 14, 19, 0, 907933)),
        ),
    ]
